name: ci

on:
  push:
    branches:
      - "azure"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go:http-server-azure
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Get Image sha256
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/go:http-server-azure"
          IMAGE_SHA256=$(docker images --no-trunc --quiet ${IMAGE_NAME})
          echo "SHA256=${IMAGE_SHA256}" >> $GITHUB_ENV
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/go:http-server-azure@${{ env.SHA256 }}"
